### ISSUE TITLE
[BUG] NextJS APP router causes enableAutoTracking to be called a lot of times

### ISSUE THREAD

**Issue by vultouri03** [microsoft/applicationinsights-react-js#129]
**Description/Screenshot**
When using the nextJS Approuter to navigate between routes, enableAutoRouteTracking sends way to many track exceptions causing the navigation times to slow down after a while.

I have a nextJS application that uses Application Insights. Due to having the need to stop navigation when some custom listeners are active, I am using useRouter from next/navigation to handle navigation. To do this I am using a mix of useRouter.push(url) and useRouter.refresh() (to make sure api calls are called after saving data). 

When I navigate between these routes using my custom navigation code I get around 500 to 1000 track pageview exceptions, which can be seen when checking the network tab in the browser inspector.

Below is an image of the way I am handling navigation
![Image](https://github.com/user-attachments/assets/e850080b-2e5f-419a-8609-80693aa20e03)

![Image](https://github.com/user-attachments/assets/3d49fcb9-655c-404a-82e0-cdc0e2af5f15)

Image of the APP Insights setup
![Image](https://github.com/user-attachments/assets/2b5fdd88-bbbe-4941-bfc1-2df67915171d)

Image of Track's in browser Insights after first load
![Image](https://github.com/user-attachments/assets/d34ffd41-0879-4b2b-b216-0462ccbfe04c)

Image of Tracks in browser Insighst after using navigation item
![Image](https://github.com/user-attachments/assets/cfaa1ff1-b843-43e2-824f-4621d302b487)

I managed to fix this issue by replacing the navigating component with

> `router.replace(url);`

And by running the Router.refresh only when it needs to be refreshed, for example after saving data that does not update in a server component.

This doesn't completely fix the issue but decreases the amount of track's that are processed after a navigation.

**Steps to Reproduce**
make sure enableAutoRouteTracking is true.
Make basic code to navigate between 2 nextJS pages using useRouter.push(url of otherpage) followed by a useRouter.refresh().
Switch between the pages using the router while the network tab is open.

 - OS/Browser: Opera GX/Edge/safari/chrome
 - SDK Version [e.g. 17]: 17.3.3
 - How you initialized the SDK:

**Expected behavior**
I expect autoRouteTracking to only give back one or two track exceptions when switching routes and not hundreds of them.

**Additional context**

**Comment by MSNev** [comment]
>  I get around 500 to 1000 track pageview exceptions

What is the contents of the exception?

This sounds like either
- You are getting a cascade of exceptions where and whatever is causing the exception is causing more exceptions
- Or you are creating / initializing MANY instances (with the same configuration) of the SDK and each instance is listening, capturing and sending the exception
  - This scenario occurs if you are creating / initializing the SDK in a base component that actually is getting called for every object (attached to the DOM or part of the shadow DOM), so it won't JUST be the exceptions but ANY automatically captured events.

**Comment by vultouri03** [comment]
Thanks for the reaction.

The SDK was indeed being initialized multiple times causing every route chance event to be captured multiple times. 
I have now changed my code to make sure it is only initialized once and am now only getting one track event per route switch which looks to be the intended behaviour.

The initialization code was being called inside of a custom made AppInsightsProvider which was rerendering a few times thus causing the SDK to be reinitialized over and over again.
