### ISSUE TITLE
[BUG] AppInsightsErrorBoundary doesn't handle errors from the children components in React 18

### ISSUE THREAD

**Issue by Igor-Pchelko** [microsoft/applicationinsights-react-js#22]
**Description/Screenshot**
AppInsightsErrorBoundary doesn't handle errors from the children components in React 18. 

**Steps to Reproduce**
Use AppInsightsErrorBoundary:
```ts
    <AppInsightsErrorBoundary onError={() => <ErrorPage500 />} appInsights={reactPlugin}>
       <SomeComponent />
    </AppInsightsErrorBoundary>
```

- Run application in dev mode 
- Use react Chrome plugin to set component to Error state

 - OS/Browser: Chrome
 - React Version: 18
 - SDK Version [e.g. 22]: 3.4.0
 - How you initialized the SDK: 
```ts
  appInsights.setup(instrumentationKey).setAutoCollectConsole(true, true).start()
```
**Expected behavior**
AppInsightsErrorBoundary should catch error state from child components and display provided onError component (e.g. ErrorPage500)

**Solution**
According to the React 18 documentation: https://reactjs.org/docs/error-boundaries.html
Error boundaries should have `getDerivedStateFromError` method to avoid recursion:
```ts
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // Update state so the next render will show the fallback UI.
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // You can also log the error to an error reporting service
    logErrorToMyService(error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      // You can render any custom fallback UI
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children; 
  }
}
```

And it might look something like this:
```ts
export default class AppInsightsErrorBoundary extends React.Component<IAppInsightsErrorBoundaryProps, IAppInsightsErrorBoundaryState> {
    state = { hasError: false };

    static getDerivedStateFromError(): { hasError: boolean } {
        // Update state so the next render will show the fallback UI.
        return { hasError: true }
      }
    
      componentDidCatch(error: Error, errorInfo: React.ErrorInfo): void {
        reactPlugin.trackException({
          error: error,
          exception: error,
          severityLevel: SeverityLevel.Error,
          properties: errorInfo,
        })
      }

    render() {
        if (this.state.hasError) {
            const { onError } = this.props;
            return React.createElement(onError);
        }

        return this.props.children;
    }
}
```

**Comment by MSNev** [comment]
Probably the best way to do this (after reading the provided error boundry link) is probably for us to create a 2nd (new/duplicated) version of the Error Boundry called something like (AppInsightsErrorBoundaryWithUI) so that anyone how has currently added their own high level error boundry to handle the UI (if I'm reading the details correctly) are not suddenly broken with the potential change in behavior.

Thoughts/Additional Suggestions?
