### ISSUE TITLE
[BUG] ReactPlugin becomes undefined after certain amount of time

### ISSUE THREAD

**Issue by eric-gonzalez-tfs** [microsoft/applicationinsights-react-js#24]
**Description/Screenshot**
I wrapped each of my components with `withAITracking` and confirmed that I am properly passing in the instance of the React Plugin.

However, after frequent navigations the app randomly crashes indicating that the React plugin is undefined.

Looks like there was [a thread about this issue](https://github.com/microsoft/ApplicationInsights-JS/issues/1053) in the old repo.

![Screen Shot 2022-10-19 at 2 57 19 PM](https://user-images.githubusercontent.com/82120345/196813763-ddc4e768-8a4e-4a0f-90b5-e55ef4c5f175.png)

**Steps to Reproduce**

Quickly navigate between pages that render components that have been wrapped with `withAITracking`

 - OS/Browser: MacOS/Chrome & Safari
 - React Version:
```
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
```
 - SDK Version [e.g. 22]:
```
    "@microsoft/applicationinsights-react-js": "^3.4.0",
    "@microsoft/applicationinsights-web": "^2.8.8",
```
 - How you initialized the SDK:
  (NOTE: Some code has been removed)
```js
export class DocsApplicationInsights {
  private reactPlugin: ReactPlugin;

  private searchListener;

  private appInsights;

  setup() {
    const { createBrowserHistory } = require('history');
    this.reactPlugin = new ReactPlugin();
    this.appInsights = new ApplicationInsights({
      config: {
        connectionString:appInsightsConnectionString,
        extensions: [this.reactPlugin],
        extensionConfig: {
          [this.reactPlugin.identifier]: { history: createBrowserHistory({ basename: '' }) },
        },
      },
    });
    this.appInsights.loadAppInsights();
    this.appInsights.setAuthenticatedUserContext(id, undefined, true);
  }

  getReactPlugin() {
    // console.log(Boolean(this.reactPlugin)); <- BTW this always outputs to true when it crashes.
    return this.reactPlugin;
  }
  }
}

export default new DocsApplicationInsights();
```

**Expected behavior**
App & components render

**Additional context**
Using docusaurus.

**Comment by MSNev** [comment]
I don't believe that there is anything specific in either the ApplicationInsights JS SDK or the plugin that would cause this, and I'm not finding any "null" assignments as in the previous thread.

Looking at the screenshot and the code, it would appear that using the `withAITracking` the provided first argument (the reactPlugin instance) that is passed into this specific usage is `undefined`, possible suggesting that the referenced variable does not exist or that nothing is passed in.
