### ISSUE TITLE
Does useTrackEvent trigger re-render?

### ISSUE THREAD

**Issue by VitaliyPotapov** [microsoft/applicationinsights-react-js#27]
As [useTrackEvent](https://github.com/microsoft/applicationinsights-react-js/blob/main/applicationinsights-react-js/src/useTrackEvent.ts) actually returns `setData` from `useState` - does it mean it will trigger component re-render every time I send event?

**Comment by Karlie-777** [comment]
@VitaliyPotapov it is returning the setData function, but not calling it setData(). So it will not directly re-rendered. And if you are using versions after React 16, calling setState with null also won't trigger an update.

**Comment by VitaliyPotapov** [comment]
Thanks Karlie! I'd like to clarify: every time I send event I actually call returned `setData()` -> state gets updated and from my understanding component will re-render. Is it correct?

I'm thinking why `useTrackEvent` is implemented as `useState + useEffect`, not just `useCallback`.

**Comment by Karlie-777** [comment]
@VitaliyPotapov Thanks for clarification! I guess you are using `useTrackEvent()` like this [example ](https://github.com/microsoft/applicationinsights-react-js/blob/2162e921ca191aa829e22812ba34ecff00787ded/sample/applicationinsights-react-sample/src/TestComponent.tsx#L11)
So return `setData()` directly for `useTrackevent()` could give you more controls on trackEvent data!

**Comment by VitaliyPotapov** [comment]
Yes I also wrap `useTrackEvent` in `useCallback`. But my question is about extra re-render that seems to occur even in your [example](https://github.com/microsoft/applicationinsights-react-js/blob/2162e921ca191aa829e22812ba34ecff00787ded/sample/applicationinsights-react-sample/src/TestComponent.tsx#L11). Please correct me if I'm wrong:

1. user clicks on button, `onClick` handler calls `setTestNumber(curTestNumber + 1)`
2. component state changed -> 1st re-render -> useEffect calls `trackEvent(testNumber)` that writes to state new `testNumber`
3. component state changed again -> 2nd re-render **(extra re-render!)**
4. process finished because no useEffect dependencies changed

My question is - could we avoid extra re-render by implementing `useCustomEvent` without writing to component state?
For example like this:

```ts
export default function useCustomEvent<T>(
  reactPlugin: ReactPlugin,
  eventName: string,
  eventData: T,
): AIReactCustomEvent<T> {
  return useCallback(() => {
    reactPlugin.trackEvent({ name: eventName }, data);
  }, [reactPlugin, data, eventName]);
}
```

**Comment by Karlie-777** [comment]
@VitaliyPotapov I thought you were referring to duplicated events are being triggered. 😊And you are correct! `useCallBack()` definitely optimizes performance by skipping re-rendering! However, downside of using `useCallback` hook is suggested [here ](https://beta.reactjs.org/reference/react/useCallback#caveats) (correct me if I am wrong)
