### ISSUE TITLE
[BUG] React 18 is not supported 

### ISSUE THREAD

**Issue by aaarichter** [microsoft/applicationinsights-react-js#4]
**Description/Screenshot**
The library requires react 17 as peer-dependency

**Steps to Reproduce**
- see https://github.com/microsoft/applicationinsights-react-js/blob/main/applicationinsights-react-js/package.json#L75

**Expected behavior**
the library should support react 18

**Additional context**
I'm using this library in a project that is currently on react 17. Trying to upgrade to react 18, `npm` is highlighting this lack of support for react 18

**Comment by MSNev** [comment]
Known issue and one of the reasons for pulling this plugin out of ApplicationInsights repo.

Related Issues from the ApplicationInsights repo
- https://github.com/microsoft/ApplicationInsights-JS/issues/1799
- https://github.com/microsoft/ApplicationInsights-JS/issues/1804
- https://github.com/microsoft/ApplicationInsights-JS/issues/1820

**Comment by MSNev** [comment]
#15

**Comment by MSNev** [comment]
We believe that this should be addressed simplistically by #15 above, this is now available as a [nightly](https://www.npmjs.com/package/@microsoft/applicationinsights-react-js/v/3.3.7-nightly.2208-05) package. If we could get some validation to confirm would be helpful.

**Comment by aaarichter** [comment]
@MSNev  hi - thanks for the new nightly - it worked for me :octocat:

**Comment by LarsKemmann** [comment]
@MSNev I can also confirm that it works for me! 🎉🚀
