### ISSUE TITLE
ApplicationInsights-JS v3 Compatibility

### ISSUE THREAD

**Issue by gao-sun** [microsoft/applicationinsights-react-js#42]
Thanks for the great work of the JS SDK and React plugin!

### Is your feature request related to a problem? Please describe.
ApplicationInsights-JS has been upgraded to v3 which is a major update, but there's no documentation of the React plugin says it is compatible with the latest JS SDK.

### Describe the solution you'd like
An official support of ApplicationInsights-JS v3.

### Describe alternatives you've considered
I've read the [Breaking Changes](https://microsoft.github.io/ApplicationInsights-JS/upgrade/v3_BreakingChanges.html) and found:

> If the extension is 100% self contained (all referenced code is included in it’s own bundle), then apart from some TypeScript typing warnings / errors the SDK will load and initialize the plugin.

It looks like the plugin should be OK, but it'll be great if we can have an official support or documentation of the v3 compatibility.

**Comment by MSNev** [comment]
Yes, we are planning during May (available early June) to upgrade and publish the react-js, reactive-native and angular plugins to work with Application Insights v3 and to implement / update any functionality required for the Dynamic Config and now exposing the optional Promise unload options.
