### ISSUE TITLE
Cross-site cookies blocking impact

### ISSUE THREAD

**Issue by clemlesne** [microsoft/applicationinsights-react-js#53]
## Description

In my Firefox setup, I intentionally enabled "Block all cross-site cookies" option. A similar option named "Prevent cross-site tracking in Safari" is enabled in Safari by default. [Google Chrome is planing to do the same mid-2023.](https://blog.google/products/chrome/updated-timeline-privacy-sandbox-milestones/)

The warning I'm providing to this issue is displayed as a warning only. How cross-site cookies blocking will impact Azure Application Analytics on the web?

## Context

OS/Browser: Firefox 115.0.3

React Version: 18.2.0

SDK Version [e.g. 22]: 3.0.2 (@microsoft/applicationinsights-core-js), 17.0.0 (@microsoft/applicationinsights-react-js)

## How you initialized the SDK

```js
import {
  AppInsightsContext,
  ReactPlugin,
} from "@microsoft/applicationinsights-react-js";
import { ApplicationInsights } from "@microsoft/applicationinsights-web";

const appInsights = new ApplicationInsights({
  config: {
    connectionString: import.meta.env.VITE_APP_INSIGHTS_CONNECTION_STR,
    extensions: [reactPlugin],
    enableAutoRouteTracking: true,
  },
});
appInsights.loadAppInsights();
```

## Full error

```
Cookie “” has been rejected as third-party.

Request to access cookie or storage on “https://westeurope-5.in.applicationinsights.azure.com//v2/track” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
```

**Comment by MSNev** [comment]
> Cookie “” has been rejected as third-party.

This is interesting, as we don't rely on cookies (send or received) for that endpoint and it's not listing what the cookie actually is....
