### ISSUE TITLE
[BUG] Error type in AppInsightsErrorBoundary after upgrading to react 18

### ISSUE THREAD

**Issue by tommyspot** [microsoft/applicationinsights-react-js#6]
**Description/Screenshot**

After I upgrade to react v18 (lib + type). I got the error when starting a react project. The error is from **AppInsightsErrorBoundary** component. So, I just investigated it's missing **children** prop in the interface.

<img width="892" alt="Screen Shot 2022-04-13 at 09 43 27" src="https://user-images.githubusercontent.com/7645519/163089530-82d4660e-282e-4230-ac74-06d46cc0891d.png">

**Steps to Reproduce**
1. Upgrade @types/react to "18.0.3".
2. Upgrade @types/react-dom to "18.0.0".
3. The error appears.

 - OS/Browser: Chrome 100.0.4896.75 
 - SDK Version [e.g. 22]: 3.2.4
 - How you initialized the SDK:

**Expected behavior**
The error should disappear.

**Additional context**

**Comment by Karlie-777** [comment]
For errors in `React.FC`, please refer https://github.com/facebook/create-react-app/pull/8177
And to solve this issue, adding fragment should help:
```
export const FooErrorBoundary: React.FC = (props) => {
    return (
        <AppInsightsErrorBoundary
            onError={() => <ErrorPage action={ErrorPageAction.ReloadPage} />}
            appInsights={fooInsightsReactPlugin}
        >
             <>
            {props.children}
            </>
        </AppInsightsErrorBoundary>
    );
};
```

**Comment by pthalamy** [comment]
@Karlie-777 Indeed this is what's changed, adding the React fragment solved the issue. Didn't think of trying this.

**Comment by MSNev** [comment]
#15
