### ISSUE TITLE
[BUG] React - withAITracking wrapper modifies the app's css

### ISSUE THREAD

**Issue by AlexisLessard** [microsoft/applicationinsights-react-js#9]
**Description/Screenshot**
By wrapping my React application in the TelemetryProvider, using `withAITracking`, the css of the app is altered, and there is no indication that `withAITracking` is actually used.
Original style:
![image](https://user-images.githubusercontent.com/10947093/114458663-7a64b580-9bad-11eb-8125-124a598c2d03.png)

Style with an withAITracking wrapper:
![image](https://user-images.githubusercontent.com/10947093/114458755-9c5e3800-9bad-11eb-9b58-d7434d9d17af.png)

The sidebar of my app is contracted and no longer fills the side. Classes are mixed up, and I don't know why.

**Steps to Reproduce**
| :zap:       Files have been altered to protect sensitive code and to highlight the essential parts |
|-----------------------------------------|

App.tsx:
```Typescript
import React from 'react';
import { createHistory, createMemorySource } from '@reach/router';

function App(): JSX.Element {

  const history = createHistory(createMemorySource('/'));
  return (
    <TelemetryProvider
      history={history}
      instrumentationKey={KEY_HERE}
    >
     { *** APP *** }
    </TelemetryProvider>
  );
}
export default App;
```

TelemetryProvider.tsx:
```Typescript
import React from 'react';
import {
  withAITracking,
  ReactPlugin,
} from '@microsoft/applicationinsights-react-js';
import { ai } from '../../services/TelemetryService';

/**
 * This Component provides telemetry with Azure App Insights
 *
 * NOTE: the package '@microsoft/applicationinsights-react-js' has a HOC withAITracking that requires this to be a Class Component rather than a Functional Component
 *
 * Voir le projet https://github.com/Azure-Samples/application-insights-react-demo pour l'utilisation
 */

export interface TelemetryProviderProps {
  history: any;
  instrumentationKey: string;
}

type TelemetryProviderState = {
  initialized: boolean;
};
class TelemetryProvider extends React.Component<
  TelemetryProviderProps,
  TelemetryProviderState
> {
  constructor(props: TelemetryProviderProps) {
    super(props);
    this.state = {
      initialized: false,
    };
  }

  componentDidMount() {
    const { history } = this.props;
    const { initialized } = this.state;
    const { instrumentationKey } = this.props;
    if (!initialized && Boolean(instrumentationKey) && Boolean(history)) {
      ai.initialize(instrumentationKey, history);
      this.setState({ initialized: true });
    }
  }

  render() {
    const { children } = this.props;
    return <>{children}</>;
  }
}

export default withAITracking(ai.reactPlugin as ReactPlugin, TelemetryProvider);
```

TelemetryService.ts:
```Typescript
import { ApplicationInsights } from '@microsoft/applicationinsights-web';
import { ReactPlugin } from '@microsoft/applicationinsights-react-js';

let reactPlugin: ReactPlugin | null = null;
let appInsights: ApplicationInsights | null = null;

/**
 * Create the App Insights Telemetry Service
 * @return {{reactPlugin: ReactPlugin, appInsights: Object, initialize: Function}} - Object
 */
const createTelemetryService = () => {
  /**
   * Initialize the Application Insights class
   * @param {string} instrumentationKey - Application Insights Instrumentation Key
   * @param {Object} browserHistory - client's browser history, supplied by the withRouter HOC
   * @return {void}
   */
  const initialize = (instrumentationKey: string, browserHistory: Object) => {
    if (!browserHistory) {
      throw new Error('Could not initialize Telemetry Service');
    }
    if (!instrumentationKey) {
      throw new Error('Instrumentation key not provided');
    }

    reactPlugin = new ReactPlugin();

    appInsights = new ApplicationInsights({
      config: {
        instrumentationKey,
        maxBatchInterval: 0,
        disableFetchTracking: false,
        extensions: [reactPlugin],
        extensionConfig: {
          [reactPlugin.identifier]: {
            history: browserHistory,
          },
        },
      },
    });

    appInsights.loadAppInsights();
  };

  return { reactPlugin, appInsights, initialize };
};

export const ai = createTelemetryService();
export const getAppInsights = () => appInsights;
```

 - OS/Browser: Chrome  89.0.4389.114
 - SDK Version [e.g. 22]: @microsoft/applicationinsights-react-js@3.1.0
 - How you initialized the SDK:

**Expected behavior**

When using the wrapper `withAITracking`, the function should return the component of the app as it is with no modifications. No change should be perceptible in the style, and the application should start tracking the metric `React Component Engaged Time (seconds)`. 

**Additional context**

- I've narrowed it down to withAITracking simply by removing it from the `TelemetryProvider`. And it worked. I could still send metrics and exceptions to Azure App Insight
- The metric   `React Component Engaged Time (seconds)` isn't showing up so far in my ressource on Azure.
- In VSCode, when I choose  `Go to Definition` on `withAITracking`, it sends me to `withAITracking.d.ts`, and not to the actual implementation, leading me to believe that the real function is never even reached. Adding console messages in `withAITracking.tsx` doesn't make them appear in the browser's console. I can't seem to modify the code and change anything in the application.
- So far, my only workaround has been to remove the `withAITracking` wrapper, but it seems like a waste. If there's no added cost, I'd like to be able to use this tool. But we'll be force to remove it for now. I don't like to differ my app compared to the sample react app too much.

**Comment by jakehockey10** [comment]
This may be specific to the app I'm working on, but it seems like styling that extra `div` with `display: contents` solves the problem for me.  According to https://www.w3schools.com/cssref/pr_class_display.php, `display: contents` does the following:

> Makes the container disappear, making the child elements children of the element the next level up in the DOM
